[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "xorg.libX11",
  "xorg.libxcb",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "libxkbcommon",
  "mesa",
  "expat",
  "glib",
  "dbus",
  "pango",
  "cairo",
  "cups",
  "alsa-lib"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx playwright install chromium"]

[start]
cmd = "node index.js"